### ISSUE TITLE
Issue with old plugin_formatter.py on py38

### ISSUE THREAD

**Issue by andy-maier** [zhmcclient/zhmc-ansible-modules#126]
Since the addition of py38 support, `make docs` fails on py38:

```
$ make docs
mkdir -p docs/gen
PYTHONPATH=../ansible/lib ../ansible/docs/bin/plugin_formatter.py -vv --type=rst --template-dir=../ansible/docs/templates --module-dir=zhmc_ansible_modules --output-dir=docs/gen/
rendering: zhmc_partition
Traceback (most recent call last):
  File "../ansible/docs/bin/plugin_formatter.py", line 315, in process_module
    text = template.render(doc)
  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "../ansible/docs/templates/plugin.rst.j2", line 90, in top-level template code
    <div>@{ desc | replace('\n', '\n    ') | html_ify }@</div>
  File "../ansible/docs/bin/plugin_formatter.py", line 85, in html_ify
    t = cgi.escape(text)
AttributeError: module 'cgi' has no attribute 'escape'

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "../ansible/docs/bin/plugin_formatter.py", line 472, in <module>
    main()
  File "../ansible/docs/bin/plugin_formatter.py", line 460, in main
    result = process_module(modname, options, env, template, outputname, module_map, aliases)
  File "../ansible/docs/bin/plugin_formatter.py", line 317, in process_module
    raise AnsibleError("Failed to render doc for %s: %s" % (fname, str(e)))
ansible.errors.AnsibleError: Failed to render doc for zhmc_ansible_modules/zhmc_partition.py: module 'cgi' has no attribute 'escape'
Makefile:336: recipe for target 'docs/gen/list_of_all_modules.rst' failed
make: *** [docs/gen/list_of_all_modules.rst] Error 1
The command "make docs" exited with 2.
```

**Comment by andy-maier** [comment]
Fixed in PR #128.
