### ISSUE TITLE
Get 'TypeError' when setting property 'ssc_dns_servers' in partition module

### ISSUE THREAD

**Issue by leopoldjuergen** [zhmcclient/zhmc-ansible-modules#34]
```
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_EyPrdo/ansible_module_zhmc_partition.py", line 980, in <module>
    main()
  File "/tmp/ansible_EyPrdo/ansible_module_zhmc_partition.py", line 964, in main
    changed, result = perform_task(module.params, module.check_mode)
  File "/tmp/ansible_EyPrdo/ansible_module_zhmc_partition.py", line 940, in perform_task
    return actions[params['state']](params, check_mode)
  File "/tmp/ansible_EyPrdo/ansible_module_zhmc_partition.py", line 840, in ensure_stopped
    process_properties(cpc, partition, params)
  File "/tmp/ansible_EyPrdo/ansible_module_zhmc_partition.py", line 636, in process_properties
    input_prop_value = type_cast(input_prop_value)
  File "/usr/local/lib/python2.7/dist-packages/zhmc_ansible_modules/utils/__init__.py", line 303, in to_unicode
    format(value, type(value)))
TypeError: Value is not a binary or unicode string: ['8.8.8.8'] <type 'list'>

fatal: [localhost]: FAILED! => {
    "changed": false, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_EyPrdo/ansible_module_zhmc_partition.py\", line 980, in <module>\n    main()\n  File \"/tmp/ansible_EyPrdo/ansible_module_zhmc_partition.py\", line 964, in main\n    changed, result = perform_task(module.params, module.check_mode)\n  File \"/tmp/ansible_EyPrdo/ansible_module_zhmc_partition.py\", line 940, in perform_task\n    return actions[params['state']](params, check_mode)\n  File \"/tmp/ansible_EyPrdo/ansible_module_zhmc_partition.py\", line 840, in ensure_stopped\n    process_properties(cpc, partition, params)\n  File \"/tmp/ansible_EyPrdo/ansible_module_zhmc_partition.py\", line 636, in process_properties\n    input_prop_value = type_cast(input_prop_value)\n  File \"/usr/local/lib/python2.7/dist-packages/zhmc_ansible_modules/utils/__init__.py\", line 303, in to_unicode\n    format(value, type(value)))\nTypeError: Value is not a binary or unicode string: ['8.8.8.8'] <type 'list'>\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 0
}
```

**Comment by andy-maier** [comment]
Fixed in PR #37.
