### ISSUE TITLE
sphinx-versions fails due to removal of deprecated function in Click

### ISSUE THREAD

**Issue by andy-maier** [zhmcclient/zhmc-ansible-modules#488]
The building of docs failed in the last all-test run: https://github.com/zhmcclient/zhmc-ansible-modules/runs/5803700274?check_suite_focus=true

with:
```
sphinx-versioning -l docs/source/conf.py build docs/source docs_build
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.2/x64/bin/sphinx-versioning", line 33, in <module>
    sys.exit(load_entry_point('sphinx-versions===1.1.3.post-am1', 'console_scripts', 'sphinx-versioning')())
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/sphinxcontrib/versioning/__main__.py", line 72, in main
    argv = kwargs.pop('args', click.get_os_args())
AttributeError: module 'click' has no attribute 'get_os_args'
```

The reason is that Click 8.1.0 removed the previously deprecated function `click.get_os_args()` and sphinx-versions has not been updated to accomodate that. Since the sphinx-versions is not currently maintained, we are using it from my fork, and this gives us a chance to fix it on that fork.

**Comment by andy-maier** [comment]
Needed a fix in my fork of spinhx-versions, and PR #490 picks up the new version here.
