### ISSUE TITLE
NameError: name 'FakedSession' is not defined on zhmc_cpc_list module

### ISSUE THREAD

**Issue by ScYang1991** [zhmcclient/zhmc-ansible-modules#574]
When I execute playbook with zhmc_cpc_list module using  ansible-playbook xxxx.yml,
I am getting error **NameError: name 'FakedSession' is not defined**.

However, when I use **sudo** ansible-playbook xxxx.yml, the error does not appear.
Is there any possibility that lack of permission on certain directory can cause this error?
I made sure the non-root user has **r** and **x** permission on python lib and packages.

My environment is:
OS - RHEL (Red Hat 8.5.0-7)
Python - 3.6.8
zhmcclient - 1.3.1
Z HMC collection - ibm-ibm_zhmc-1.1.1

Attached the playbook and error log below.

Thanks.

**(executed playbook below)**
```
- name: get CPC list
  hosts: localhost
  gather_facts: no
  collections:
    - ibm.ibm_zhmc
  vars_prompt:
    - name: hmc_user
      prompt: "Enter your HMC username"
      private: no
    - name: hmc_password
      prompt: "Enter your HMC password"
      private: yes  
  tasks:
    - name: list managed CPC 
      zhmc_cpc_list:
        hmc_host: "{{ hmc_ip }}"
        hmc_auth:
          userid: "{{ hmc_user }}"
          password: "{{ hmc_password }}"
          verify: False
      register: cpc_list

    - debug:
        var: cpc_list
```

**(error log of the task)**
```
TASK [list managed cpc] ********************************************************************************************************************
task path: /etc/ansible/trial/testcon/cpc_list.yml:14
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: kashiid1
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /tmp `"&& mkdir "` echo /tmp/ansible-tmp-1666587388.9871688-962772-214546867727507 `" && echo ansible-tmp-1666587388.9871688-962772-214546867727507="` echo /tmp/ansible-tmp-1666587388.9871688-962772-214546867727507 `" ) && sleep 0'
Using module file /etc/ansible/trial/collections/ansible_collections/ibm/ibm_zhmc/plugins/modules/zhmc_cpc_list.py
<localhost> PUT /home/kashiid1/.ansible/tmp/ansible-local-9627651_6fmp_c/tmp7bwq2cr_ TO /tmp/ansible-tmp-1666587388.9871688-962772-214546867727507/AnsiballZ_zhmc_cpc_list.py
<localhost> EXEC /bin/sh -c 'chmod u+x /tmp/ansible-tmp-1666587388.9871688-962772-214546867727507/ /tmp/ansible-tmp-1666587388.9871688-962772-214546867727507/AnsiballZ_zhmc_cpc_list.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python3.6 /tmp/ansible-tmp-1666587388.9871688-962772-214546867727507/AnsiballZ_zhmc_cpc_list.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /tmp/ansible-tmp-1666587388.9871688-962772-214546867727507/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible-tmp-1666587388.9871688-962772-214546867727507/AnsiballZ_zhmc_cpc_list.py", line 102, in <module>
    _ansiballz_main()
  File "/tmp/ansible-tmp-1666587388.9871688-962772-214546867727507/AnsiballZ_zhmc_cpc_list.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/tmp/ansible-tmp-1666587388.9871688-962772-214546867727507/AnsiballZ_zhmc_cpc_list.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.ibm.ibm_zhmc.plugins.modules.zhmc_cpc_list', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_zhmc_cpc_list_payload_wlbx801r/ansible_zhmc_cpc_list_payload.zip/ansible_collections/ibm/ibm_zhmc/plugins/modules/zhmc_cpc_list.py", line 331, in <module>
  File "/tmp/ansible_zhmc_cpc_list_payload_wlbx801r/ansible_zhmc_cpc_list_payload.zip/ansible_collections/ibm/ibm_zhmc/plugins/modules/zhmc_cpc_list.py", line 313, in main
  File "/tmp/ansible_zhmc_cpc_list_payload_wlbx801r/ansible_zhmc_cpc_list_payload.zip/ansible_collections/ibm/ibm_zhmc/plugins/modules/zhmc_cpc_list.py", line 230, in perform_list
  File "/tmp/ansible_zhmc_cpc_list_payload_wlbx801r/ansible_zhmc_cpc_list_payload.zip/ansible_collections/ibm/ibm_zhmc/plugins/module_utils/common.py", line 639, in get_session
NameError: name 'FakedSession' is not defined
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible-tmp-1666587388.9871688-962772-214546867727507/AnsiballZ_zhmc_cpc_list.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/tmp/ansible-tmp-1666587388.9871688-962772-214546867727507/AnsiballZ_zhmc_cpc_list.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/tmp/ansible-tmp-1666587388.9871688-962772-214546867727507/AnsiballZ_zhmc_cpc_list.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.ibm.ibm_zhmc.plugins.modules.zhmc_cpc_list', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_zhmc_cpc_list_payload_wlbx801r/ansible_zhmc_cpc_list_payload.zip/ansible_collections/ibm/ibm_zhmc/plugins/modules/zhmc_cpc_list.py\", line 331, in <module>\n  File \"/tmp/ansible_zhmc_cpc_list_payload_wlbx801r/ansible_zhmc_cpc_list_payload.zip/ansible_collections/ibm/ibm_zhmc/plugins/modules/zhmc_cpc_list.py\", line 313, in main\n  File \"/tmp/ansible_zhmc_cpc_list_payload_wlbx801r/ansible_zhmc_cpc_list_payload.zip/ansible_collections/ibm/ibm_zhmc/plugins/modules/zhmc_cpc_list.py\", line 230, in perform_list\n  File \"/tmp/ansible_zhmc_cpc_list_payload_wlbx801r/ansible_zhmc_cpc_list_payload.zip/ansible_collections/ibm/ibm_zhmc/plugins/module_utils/common.py\", line 639, in get_session\nNameError: name 'FakedSession' is not defined\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

**(when run with sudo)**
```
PLAY [get cpc list] ************************************************************************************************************************

TASK [list managed cpc] ********************************************************************************************************************
ok: [localhost]

TASK [debug] *******************************************************************************************************************************
ok: [localhost] => {
    "cpc_list": {
        "changed": false,
        "cpcs": [
            {
                "dpm_enabled": false,
                "has_unacceptable_status": true,
                "is_managed": true,
                "name": "CPU1",
                "se_version": "2.13.1",
                "status": "operating"
            }
        ],
        "failed": false
    }
}

PLAY RECAP *********************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

**Comment by andy-maier** [comment]
Sorry for the delay. I'll look into this.

**Comment by andy-maier** [comment]
It is possible that the Python environment you are using is different between using and not using sudo.

The error means that the zhmcclient_mock package is not in the module search path. It comes as part of the zhmcclient package from Pypi, so you need to investigate whether it exists and what its file permissions are.

Can you please try the following and post the results:

```
ls -ld $(python -c "import os,zhmcclient; print(os.path.dirname(zhmcclient.__file__))")*
ls -ld $(sudo python -c "import os,zhmcclient; print(os.path.dirname(zhmcclient.__file__))")*
```

In a virtual Python environment with Python 3.7 on macOS, the output in both cases looks like:

```
drwxr-xr-x  43 maiera  staff  1376 Nov 28 18:27 /Users/maiera/virtualenvs/zhmcam37/lib/python3.7/site-packages/zhmcclient
drwxr-xr-x  10 maiera  staff   320 Nov 28 18:27 /Users/maiera/virtualenvs/zhmcam37/lib/python3.7/site-packages/zhmcclient-1.5.0.dist-info
drwxr-xr-x   8 maiera  staff   256 Nov 28 18:27 /Users/maiera/virtualenvs/zhmcam37/lib/python3.7/site-packages/zhmcclient_mock
```

**Comment by andy-maier** [comment]
What is also true is that the checking for a missing zhmcclient_mock module could be better. For imports done in the module files directly, there is proper error handling. However, for the modules imported in the common.py file, there is no error handling at all. That definitely needs to be improved.

**Comment by andy-maier** [comment]
With the error handling improvement in PR TBD, the error message becomes more understandable in case the zhmcclient_mock module directory is missing or cannot be imported from:

```
TASK [list managed CPC] ********************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ModuleNotFoundError: No module named 'zhmcclient_mock'
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to import the required Python library (zhmcclient_mock) on Andreass-MBP-2.fritz.box's Python /Users/maiera/virtualenvs/zhmcam37/bin/python. Please read module documentation and install in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"}
```

**Comment by andy-maier** [comment]
I have marked the error as fixed due to the PR that improves the handling, but please still investigate the zhmcclient_mock module directory in your Python environment, as described above, and post it here.
